name: manage-azure-policy-b93509a2
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policy/policies/_Outsystems_Backups_Configure_backup_on_virtual_machines_with_a_given_tag_to_existing_recovery_services_vault_in_same_location_9f403b23-6eda-45cf-ba1e-85d8185153e2/**'
#      - .github/workflows/manage-azure-policy-b93509a2.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_b93509a2}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policy/policies/_Outsystems_Backups_Configure_backup_on_virtual_machines_with_a_given_tag_to_existing_recovery_services_vault_in_same_location_9f403b23-6eda-45cf-ba1e-85d8185153e2/**
